const config = {
  AdminEmail: "#{REACT-APP-ADMIN-EMAIL}#",

  APIS_PROTECT: "#{NODE-PROTECT-API-KEY}#",

  AUTH_API_KEY: "#{AUTH-API-KEY}#",

  CLIENT_BASE_URL: "#{REACT-CLIENT-BASE-URL}#",
  API: "#{REACT-NODE-API}#",
  AUTH_API: "#{REACT-AUTH-API}#",
  PAYMENT_API: "#{REACT-PAYMENT-API}#",

  GOOGLE_PLACES_KEY: "#{REACT-APP-GOOGLE-MAPS-KEY}#",
  GOOGLE_MAPS_KEY: "#{REACT-APP-GOOGLE-MAPS-KEY}#",
  STRIPE_PUBLISHABLE_KEY: "#{STRIPE-PUBLISHABLE-KEY}#",
  // appId: "#{REACT-appId}#",
  emailId: "#{REACT-APP-EMAIL-ID}#",

  // PAYSTACK_KEYS = "development"
  REACT_APP_PS_PUBLIC_TEST_KEY: "#{REACT-APP-PS-PUBLIC-TEST-KEY-DEV}#",
  REACT_APP_PS_PUBLIC_LIVE_KEY: "#{REACT-APP-PS-PUBLIC-LIVE-KEY-DEV}#",
};

export default config;
